### ISSUE TITLE
Tails' Tail Attack Effect Disappears

### ISSUE THREAD

**Issue by Hackche** [michael-fadely/sadx-onion-blur#9]
This one is weird. When the Lantern Engine mod from x-hax is enabled in tangent with the Onion Blur, Tails' Tail Attack effect doesn't appear in some spots of the map, I'm not entirely sure the exact ones but it doesn't appear in Station Square or in the Ice Cave with these two mods on. I checked to make sure it wasn't one or the other, it only happens when they're both on, regardless of any other mods from what I concluded in my tests.

![](https://cdn.discordapp.com/attachments/453772675253534721/455305799238025236/unknown.png)

![](https://cdn.discordapp.com/attachments/453772675253534721/455309058023620608/unknown.png)

![](https://cdn.discordapp.com/attachments/453772675253534721/455468645154291737/unknown.png)

A video providing better examples:
https://youtu.be/Ez3Gk6-iA5A
(Apologies for the choppy frame rate I don't do this often)

**Comment by PiKeyAr** [comment]
#8

**Comment by Hackche** [comment]
I actually went ahead and read that one after I posted this, sorry

**Comment by michael-fadely** [comment]
Fixed by #11
